[project]
name = "p_ai"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.121",
  "uvicorn[standard]",
  "pydantic-settings",
  "sqlalchemy>=2.0",
  "psycopg2-binary",
  "boto3",
  "pymupdf",
  "python-multipart",
  "pgvector"
]

[tool.black]
line-length = 100
